name: wind
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  email_validator: ^2.1.17
  intl: ^0.18.1
  url_launcher: ^6.1.14
  fl_chart: ^0.63.0
  dots_indicator: ^3.0.0
  logger: ^2.0.2+1
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - config/app_config_dev.json
    - config/app_config_prod.json
    - assets/images/
    - assets/texts/
